irc:
    enabled: true
    operator: "!"
    CodeTalk:
        server: "irc.codetalk.io"
        port: 6697
        ssl: true
        channel: "#slight"
        nickname: "slight-ci"
notifications:
    jobs: "privmsg"
    issues: "notice"
    commands: "notice"